### ISSUE TITLE
GPDR checklist

### ISSUE THREAD

**Issue by christalib** [tosdr/edit.tosdr.org#334]
Inspired from [here](https://github.com/tootsuite/mastodon/issues/7280)

* [ ] updated version of our ToS @hugoroy 
* [x] allow user to delete their data (still a work in progress, I've started something there but hasn't finished it) @piks3l #335 
* [ ] allow user to export all its data (maybe we could make it a cool way to export user's point and contributions ?)
